---
title: "R Notebook"
output: html_notebook
---

---
title: "ADS2002"
author: "Priyom Sarkar"
date: "03/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fpp3)
library(data.table)
```

```{r}
options(pillar.sigfig = 7)


# Extend these frequency lists as required
LOW_FREQUENCIES <- c("4_seconds", "minutely", "10_minutes", "15_minutes", "half_hourly", "hourly")
LOW_FREQ_VALS <- c("4 sec", "1 min", "10 min", "15 min", "30 min", "1 hour")
HIGH_FREQUENCIES <- c("daily", "weekly", "monthly", "quarterly", "yearly")
HIGH_FREQ_VALS <- c("1 day", "1 week", "1 month", "3 months", "1 year")
FREQUENCIES <- c(LOW_FREQUENCIES, HIGH_FREQUENCIES)
FREQ_VALS <- c(LOW_FREQ_VALS, HIGH_FREQ_VALS)


# Create a hashmap containing possible frequency key-value pairs
FREQ_MAP <- list()

for(f in seq_along(FREQUENCIES))
  FREQ_MAP[[FREQUENCIES[f]]] <- FREQ_VALS[f]


# This function converts the contents in a .tsf file into a tsibble or a dataframe and returns it along with other meta-data of the dataset: frequency, horizon, whether the dataset contains missing values and whether the series have equal lengths
#
# Parameters
# file - .tsf file path
# value_column_name - Any name that is preferred to have as the name of the column containing series values in the returning tsibble
# key - The name of the attribute that should be used as the key when creating the tsibble. If doesn't provide, a data frame will be returned instead of a tsibble
# index - The name of the time attribute that should be used as the index when creating the tsibble. If doesn't provide, it will search for a valid index. When no valid index found, a data frame will be returned instead of a tsibble
convert_tsf_to_tsibble <-   function(file, value_column_name = "series_value", key = NULL, index = NULL){
    if(is.character(file)) {
      file <- file(file, "r")
      on.exit(close(file))
    }
    if(!inherits(file, "connection"))
      stop("Argument 'file' must be a character string or connection.")
    if(!isOpen(file)) {
      open(file, "r")
      on.exit(close(file))
    }

    # Read meta-data
    col_names <- NULL
    col_types <- NULL
    frequency <- NULL
    forecast_horizon <- NULL
    contain_missing_values <- NULL
    contain_equal_length <- NULL
    index_var <- NULL

    line <- readLines(file, n = 1) #n is no: of lines to read

    while(length(line) && regexpr('^[[:space:]]*@data', line, perl = TRUE) == -1) { #Until read @data, run this loop (-1 indicate no match with the regular expression yet)

      if(regexpr('^[[:space:]]*@', line, perl = TRUE) > 0) { #This condition will be true for lines starting with @

        con <- textConnection(line)
        line <- scan(con, character(), quiet = TRUE) #Creating a vector containing the words in a line (ex: "@attribute" "series_name" "string")
        close(con)

        if(line[1] == "@attribute"){
          if(length(line) != 3)  #Attributes have both name and type
            stop("Invalid meta-data specification.")

          if(is.null(index) & line[3] == "date")
            index_var <- line[2]
            
          col_names <- c(col_names, line[2])
          col_types <- c(col_types, line[3])
        }else{
          if(length(line) != 2) #Other meta-data have only values
            stop("Invalid meta-data specification.")

          if(line[1] == "@frequency")
            frequency <- line[2]
          else if(line[1] == "@horizon")
            forecast_horizon <- as.numeric(line[2])
          else if(line[1] == "@missing")
            contain_missing_values <- as.logical(line[2])
          else if(line[1] == "@equallength")
            contain_equal_length <- as.logical(line[2])
        }
      }
      line <- readLines(file, n = 1)
    }

    if(length(line) == 0)
      stop("Missing data section.")
    if(is.null(col_names))
      stop("Missing attribute section.")

    line <- readLines(file, n = 1)

    if(length(line) == 0)
      stop("Missing series information under data section.")

    for(col in col_names)
      assign(col, NULL)

    values <- NULL
    row_count <- 0

    # Get data
    while(length(line) != 0){
      full_info <- strsplit(line, ":")[[1]]

      if(length(full_info) != length(col_names)+1)
        stop("Missing attributes/values in series.")

      series <- strsplit(tail(full_info, 1), ",")[[1]]
      series[which(series == "?")] <- NA
      series <- as.numeric(series)
      
      if(all(is.na(series)))
        stop("All series values are missing. A given series should contains a set of comma separated numeric values. At least one numeric value should be there in a series.")

      values <- c(values, series)
      row_count <- row_count + length(series)

      attributes <- head(full_info, length(full_info)-1)

      for(col in seq_along(col_names)){

        att <- eval(parse(text=col_names[col]))

        #This format supports 3 attribute types: string, numeric and date
        if(col_types[col] == "date"){
          if(is.null(frequency))
            stop("Frequency is missing.")
          else{
            if(frequency %in% LOW_FREQUENCIES)
                start_time <- as.POSIXct(attributes[col], format = "%Y-%m-%d %H-%M-%S", tz = "UTC")
            else if(frequency %in% HIGH_FREQUENCIES)
                start_time <- as.Date(attributes[col], format = "%Y-%m-%d %H-%M-%S")
            else
                stop("Invalid frequency.")

            if(is.na(start_time))
              stop("Incorrect timestamp format. Specify your timestamps as YYYY-mm-dd HH-MM-SS")
          }

          timestamps <- seq(start_time, length.out = length(series), by = FREQ_MAP[[frequency]])
          
          if(is.null(att))
            att <- timestamps
          else
            att[(length(att) + 1) : ((length(att) + length(timestamps)))] <- timestamps
        }else{
          if(col_types[col] == "numeric")
            attributes[col] <- as.numeric(attributes[col])
          else if(col_types[col] == "string")
            attributes[col] <- as.character(attributes[col])
          else
            stop("Invalid attribute type.")

          if(is.na(attributes[col]))
            stop("Invalid attribute values.")

          att <- append(att, rep(attributes[col], length(series)))
        }
        assign(col_names[col], att)
      }

      line <- readLines(file, n = 1)
    }

    data <- as.data.frame(matrix(nrow = row_count, ncol = length(col_names) + 1))
    colnames(data) <- c(col_names, value_column_name)

    for(col in col_names)
      data[[col]] <- eval(parse(text = col))

    data[[value_column_name]] <- values

    if(!(is.null(key))){
      if(!(key %in% col_names))
        stop("Invalid key. Cannot convert data into tsibble format.")
      else{
        if(is.null(index)){
          if(is.null(index_var))
            cat("Index is not provided. No valid index found in data. Returning a dataframe.")
          else
            data <- tsibble:::build_tsibble(x = data, key = key, index = index_var, ordered = F)
        }else{
          if(!(index %in% col_names))
            stop("Invalid index Cannot convert data into tsibble format.")
          else
            data <- tsibble:::build_tsibble(x = data, key = key, index = index, ordered = F)
        }
      }
    }else{
      cat("Key is not provided. Returning a dataframe.")
    }

    list(data, frequency, forecast_horizon, contain_missing_values, contain_equal_length)
}


# Example of usage
# loaded_data <- convert_tsf_to_tsibble(file.path("TSForecasting", "tsf_data", "sample.tsf", fsep = "/"), "series_value", "series_name", "start_timestamp")
# tsibble_data <- loaded_data[[1]]
# frequency <- loaded_data[[2]]
# forecast_horizon <- loaded_data[[3]]
# contain_missing_values <- loaded_data[[4]]
# contain_equal_length <- loaded_data[[5]]
```

```{r}
data1 <- convert_tsf_to_tsibble(file.path("C:/Users/Priyo/OneDrive/Documents/phase_1_data.tsf"), "series_value", "series_name", "start_timestamp")
data1 <- Map(as.data.frame, data1)
dfrData <- rbindlist(data1, fill = TRUE)
dfrData$`dots[[1L]][[2L]]` <- NULL
dfrData$`dots[[1L]][[4L]]` <- NULL
dfrData$`dots[[1L]][[5L]]` <- NULL
clean <- na.omit(dfrData)
```

```{r}
data_Building0 <- dfrData %>%
  filter(series_name == 'Building0')
data_Building1 <- dfrData %>%
  filter(series_name == 'Building1')
data_Building6 <- dfrData %>%
  filter(series_name == 'Building6')
data_Building3 <- dfrData %>%
  filter(series_name == 'Building3')
data_Building4 <- dfrData %>%
  filter(series_name == 'Building4')
data_Building5 <- dfrData %>%
  filter(series_name == 'Building5')
data_Solar0 <- dfrData %>%
  filter(series_name == 'Solar0')
data_Solar1 <- dfrData %>%
  filter(series_name == 'Solar1')
data_Solar2 <- dfrData %>%
  filter(series_name == 'Solar2')
data_Solar3 <- dfrData %>%
  filter(series_name == 'Solar3')
data_Solar4 <- dfrData %>%
  filter(series_name == 'Solar4')
data_Solar5 <- dfrData %>%
  filter(series_name == 'Solar5')
```

```{r}
data_Building0 <- as_tsibble(data_Building0, index = start_timestamp)
data_Building1 <- as_tsibble(data_Building1, index = start_timestamp)
data_Building4 <- as_tsibble(data_Building4, index = start_timestamp)
data_Building5 <- as_tsibble(data_Building5, index = start_timestamp)
data_Building6 <- as_tsibble(data_Building6, index = start_timestamp)
data_Building3 <- as_tsibble(data_Building3, index = start_timestamp)
data_Solar0 <- as_tsibble(data_Solar0, index = start_timestamp)
data_Solar1 <- as_tsibble(data_Solar1, index = start_timestamp)
data_Solar2 <- as_tsibble(data_Solar2, index = start_timestamp)
data_Solar3 <- as_tsibble(data_Solar3, index = start_timestamp)
data_Solar4 <- as_tsibble(data_Solar4, index = start_timestamp)
data_Solar5 <- as_tsibble(data_Solar5, index = start_timestamp)
```



```{r}
library(imputeTS)
```


```{r}
data_Building0_out <- data_Building0 %>%
  filter(data_Building0$series_value < 518)

data_Building3_out <- data_Building3 %>%
  filter(data_Building3$series_value < 1229)

data_Building0_out <- tsibble::fill_gaps(data_Building0_out, .full = TRUE)
data_Building3_out <- tsibble::fill_gaps(data_Building3_out, .full = TRUE)

data_Building3_out$series_name <- data_Building3_out$series_name %>% replace_na('Building3')
data_Building0_out$series_name <- data_Building0_out$series_name %>% replace_na('Building0')
```




```{r}
data_Building0_condensed <- data_Building0 %>%
  filter_index('2019-10-10 00:15:00' ~ '2020-09-30 23:45:00') 
data_Building6_condensed <- data_Building6 %>%
  filter_index('2019-10-24 00:15:00' ~ '2020-09-30 23:45:00')
data_Building0_condensed <- na_interpolation(data_Building0_condensed, option = 'linear')
data_Building6_condensed <- na_interpolation(data_Building6_condensed, option = 'linear')
data_Building3_linear <- na_interpolation(data_Building3, option = 'linear')
data_Building1_linear <- na_interpolation(data_Building1, option = 'linear')
data_Building4_random <- na_random(data_Building4)
data_Building5_random <- na_random(data_Building5)
```


```{r}
autoplot(data_Building0_condensed) + ggtitle('Electricity Usage of Building0') + xlab('Date') + ylab('Value')
autoplot(data_Building6_condensed) + ggtitle('Electricity Usage of Building6') + xlab('Date') + ylab('Value')
autoplot(data_Building3_linear) + ggtitle('Electricity Usage of Building3') + xlab('Date') + ylab('Value')
autoplot(data_Building1_linear) + ggtitle('Electricity Usage of Building1') + xlab('Date') + ylab('Value')
autoplot(data_Building5_random) + ggtitle('Electricity Usage of Building5') + xlab('Date') + ylab('Value')
autoplot(data_Building4_random) + ggtitle('Electricity Usage of Building4') + xlab('Date') + ylab('Value')
```


```{r}
#for transforming data finding the lambda value for stabilizing value
data_Building0_condensed %>%
  features(series_value, features = guerrero)
data_Building6_condensed %>%
  features(series_value, features = guerrero)
data_Building3_linear %>%
  features(series_value, features = guerrero)
data_Building1_linear %>%
  features(series_value, features = guerrero)
data_Building5_random %>%
  features(series_value, features = guerrero)
data_Building4_random %>%
  features(series_value, features = guerrero)
```

```{r}
lambda0 <- 1.999927	
lambda1 <- 0.005881298	
lambda3 <- 0.3554348	
lambda4 <- -0.2647104	
lambda5 <- 0.7262362		
lambda6 <- 0.08591926	
```

```{r}
data_Building0_condensed_box <- data_Building0_condensed %>%
  autoplot(box_cox(series_value, lambda0)) + ggtitle('Electricity Usage of Building0') + xlab('Date') + ylab('Transformed Value')
data_Building6_condensed_box <- data_Building6_condensed %>%
  autoplot(box_cox(series_value, lambda6)) + ggtitle('Electricity Usage of Building6') + xlab('Date') + ylab('Transformed Value')
data_Building3_linear_box <- data_Building3_linear %>%
  autoplot(box_cox(series_value, lambda3)) + ggtitle('Electricity Usage of Building3') + xlab('Date') + ylab('Transformed Value')
data_Building1_linear_box <- data_Building1_linear %>%
  autoplot(box_cox(series_value, lambda1)) + ggtitle('Electricity Usage of Building1') + xlab('Date') + ylab('Transformed Value')
data_Building4_random_box <- data_Building4_random %>%
  autoplot(box_cox(series_value, lambda4)) + ggtitle('Electricity Usage of Building4') + xlab('Date') + ylab('Transformed Value')
data_Building5_random_box <- data_Building5_random %>%
  autoplot(box_cox(series_value, lambda6)) + ggtitle('Electricity Usage of Building5') + xlab('Date') + ylab('Transformed Value')

```

```{r}
data_Building0_condensed_box
data_Building6_condensed_box
data_Building3_linear_box
data_Building1_linear_box
data_Building4_random_box
data_Building5_random_box
```

```{r}
data_Building6_condensed %>%
  gg_tsdisplay(series_value, plot_type = 'partial')
```

```{r}
data_Building0_condensed %>%
  features(series_value, unitroot_nsdiffs)
data_Building6_condensed %>%
  features(series_value, unitroot_nsdiffs)
data_Building3_linear %>%
  features(series_value, unitroot_nsdiffs)
data_Building1_linear %>%
  features(series_value, unitroot_nsdiffs)
data_Building4_random %>%
  features(series_value, unitroot_nsdiffs)
data_Building5_random %>%
  features(series_value, unitroot_nsdiffs)
```
```{r}
data_Building1_linear %>%
  features(series_value, unitroot_kpss())
```

```{r}
data_Building0_condensed %>%
  mutate(diff_val = difference(series_value)) %>%
  features(diff_val, unitroot_ndiffs)
data_Building3_linear %>%
  mutate(diff_val = difference(series_value)) %>%
  features(diff_val, unitroot_ndiffs)
data_Building1_linear %>%
  mutate(diff_val = difference(series_value)) %>%
  features(diff_val, unitroot_nsdiffs)
data_Building4_random %>%
  mutate(diff_val = difference(series_value)) %>%
  features(diff_val, unitroot_ndiffs)
data_Building5_random %>%
  mutate(diff_val = difference(series_value)) %>%
  features(diff_val, unitroot_ndiffs)
```
####START HERE####
```{r}
data_Building0_condensed %>%
  gg_tsdisplay(
    difference(series_value),
    plot_type = 'partial'
  )
```

```{r}
data_Building3_linear %>%
  gg_tsdisplay(
    difference(series_value),
    plot_type = 'partial'
  )
```

```{r}
data_Building1_linear %>%
  gg_tsdisplay(
    difference(series_value),
    plot_type = 'partial'
  )
```



```{r}
data_Building4_random %>%
  gg_tsdisplay(
    difference(series_value),
    plot_type = 'partial'
  )
```




```{r}
data_Building5_random %>%
  gg_tsdisplay(
    difference(series_value),
    plot_type = 'partial'
  )
```

```{r}
my_dcmp_spec <- decomposition_model(
  STL(series_value  ~ season(period = 96) + season(period = 96*7)),
                                     ETS(season_adjust ~ season("A"))
  )
```

```{r}
dcmp_spec <- decomposition_model(
  STL(series_value  ~ season(period = 48) + season(period = 48*15)),
                                     ETS(season_adjust ~ season("A"))
  )
```


```{r}
library(fable.prophet)
```



```{r}
train_data_Building0_condensed <- data_Building0_condensed %>%
  filter_index('2019-10-10 00:15:00' ~ '2020-08-31 23:45:00')
fit_building0 <- train_data_Building0_condensed %>%
  model(auto = ARIMA(series_value),
        smodel = SNAIVE(series_value),
        stl = my_dcmp_spec)

fit_building0_fc <- fit_building0 %>%
  forecast(h = 2880)

accuracy(fit_building0_fc, data_Building0_condensed)
```


```{r}
train_data_Building6_condensed <- data_Building6_condensed %>%
  filter_index('2019-10-24 00:15:00' ~ '2020-08-31 23:45:00')
fit_building6 <- train_data_Building6_condensed %>%
  model(auto = ARIMA(series_value),
        smodel = SNAIVE(series_value),
        stl = my_dcmp_spec)


fit_building6_fc <- fit_building6 %>%
  forecast(h = 2880)

accuracy(fit_building6_fc, data_Building6_condensed)
```

```{r}
train_data_Building3_linear <- data_Building3_linear %>%
  filter_index('2016-03-01 04:15:00' ~ '2020-08-31 23:45:00')
fit_building3 <- train_data_Building3_linear %>%
  model(auto = ARIMA(series_value),
        smodel = SNAIVE(series_value),
        stl = my_dcmp_spec)

fit_building3_fc <- fit_building3 %>%
  forecast(h = 2880)


accuracy(fit_building3_fc, data_Building3_linear)
```

```{r}
train_data_Building1_linear <- data_Building1_linear %>%
  filter_index('2019-01-09 23:15:00' ~ '2020-08-31 23:45:00')
fit_building1 <- train_data_Building1_linear %>%
  model(arima400010 = ARIMA(series_value ~ pdq(4,0,0) + PDQ(0,1,0)),
        smodel = SNAIVE(series_value),
        stl = my_dcmp_spec)

fit_building1_fc <- fit_building1 %>%
  forecast(h = 2880)


accuracy(fit_building1_fc, data_Building1_linear)
```


```{r}
train_data_Building4_random <- data_Building4_random %>%
  filter_index('2019-07-03 04:45:00' ~ '2020-08-31 23:45:00')
fit_building4 <- train_data_Building4_random %>%
  model(auto = ARIMA(series_value),
        smodel = SNAIVE(series_value),
        stl = my_dcmp_spec)

fit_building4_fc <- fit_building4 %>%
  forecast(h = 2880)

accuracy(fit_building4_fc, data_Building4_random)
```

```{r}
train_data_Building5_random <- data_Building5_random %>%
  filter_index('2019-07-25 23:00:00' ~ '2020-08-31 23:45:00')
fit_building5 <- train_data_Building5_random %>%
  model(auto = ARIMA(series_value),
        smodel = SNAIVE(series_value),
        stl = my_dcmp_spec)

fit_building5_fc <- fit_building5 %>%
  forecast(h = 2880)


accuracy(fit_building5_fc, data_Building5_random)

```

```{r}
fit_building5_fc
```
######STOP HERE#######
```{r}
train_data_Solar0 <- data_Solar0 %>%
  filter_index('2020-04-25 23:00:00' ~ '2020-08-31 23:45:00')
fit_solar0 <- train_data_Solar0%>%
  model(auto = ARIMA(series_value),
        smodel = SNAIVE(series_value),
        stl = my_dcmp_spec)

fit_solar0_fc <- fit_solar0 %>%
  forecast(h = 2880)


accuracy(fit_solar0_fc, data_Solar0)

```

```{r}
train_data_Solar1 <- data_Solar1 %>%
  filter_index('2020-04-25 23:00:00' ~ '2020-08-31 23:45:00')
fit_solar1 <- train_data_Solar1 %>%
  model(auto = ARIMA(series_value),
        smodel = SNAIVE(series_value),
        stl = my_dcmp_spec)

fit_solar1_fc <- fit_solar1 %>%
  forecast(h = 2880)


accuracy(fit_solar1_fc, data_Solar1)

```

```{r}
train_data_Solar2 <- data_Solar2 %>%
  filter_index('2020-04-25 23:00:00' ~ '2020-08-31 23:45:00')
fit_solar2 <- train_data_Solar2 %>%
  model(auto = ARIMA(series_value),
        smodel = SNAIVE(series_value),
        stl = my_dcmp_spec)

fit_solar2_fc <- fit_solar2 %>%
  forecast(h = 2880)


accuracy(fit_solar2_fc, data_Solar2)

```

```{r}
train_data_Solar3 <- data_Solar3 %>%
  filter_index('2020-04-25 23:00:00' ~ '2020-08-31 23:45:00')
fit_solar3 <- train_data_Solar3 %>%
  model(auto = ARIMA(series_value),
        smodel = SNAIVE(series_value),
        stl = my_dcmp_spec)

fit_solar3_fc <- fit_solar3 %>%
  forecast(h = 2880)


accuracy(fit_solar3_fc, data_Solar3)

```

```{r}
train_data_Solar4 <- data_Solar4 %>%
  filter_index('2020-04-25 23:00:00' ~ '2020-08-31 23:45:00')
fit_solar4 <- train_data_Solar4 %>%
  model(auto = ARIMA(series_value),
        smodel = SNAIVE(series_value),
        stl = my_dcmp_spec)

fit_solar4_fc <- fit_solar4 %>%
  forecast(h = 2880)


accuracy(fit_solar4_fc, data_Solar4)

```

```{r}
train_data_Solar5 <- data_Solar5 %>%
  filter_index('2020-04-25 23:00:00' ~ '2020-08-31 23:45:00')
fit_solar5 <- train_data_Solar5 %>%
  model(auto = ARIMA(series_value),
        smodel = SNAIVE(series_value),
        stl = my_dcmp_spec)

fit_solar5_fc <- fit_solar5 %>%
  forecast(h = 2880)


accuracy(fit_solar5_fc, data_Solar5)

```


###IGNORE###
```{r}
my_dcmp_spec <- decomposition_model(
  STL(series_value  ~ season(period = 96) + season(period = 96*15)),
                                     ETS(season_adjust ~ season("A"))
  )
```


```{r}
data_Building1_linear %>%
  model(STL(series_value ~ season(period = 96) + season(period = 96*7))) %>%
  components() %>%
  autoplot() + ggtitle("STL decomposition for Building 1")
```



```{r}
fit_building1_fc  %>%
  autoplot(data_Building1_spline, color = 'red') + ylim(c(0,100))
```

```{r}
Oct_fit_building0 <- data_Building0_condensed %>%
  model(STl = my_dcmp_spec)

Oct_fit_building0_fc <- Oct_fit_building0 %>%
  forecast(h = 2880)

p1 <- Oct_fit_building0_fc %>%
  autoplot() + ylim(c(0,100)) + ggtitle("Building 0 Consumption Forecasts for October")
  
```

```{r}
Oct_fit_building1 <- data_Building1_linear %>%
  model(STl = my_dcmp_spec)

Oct_fit_building1_fc <- Oct_fit_building1 %>%
  forecast(h = 2880)

p2 <- Oct_fit_building1_fc %>%
  autoplot() + ylim(c(0,50)) + ggtitle("Building 1 Consumption Forecasts")
  
```

```{r}
Oct_fit_building3 <- data_Building3_linear %>%
  model(STl = my_dcmp_spec)

Oct_fit_building3_fc <- Oct_fit_building3 %>%
  forecast(h = 2880)

p3 <- Oct_fit_building3_fc %>%
  autoplot(color = 'green') + ylim(c(0,600)) + ggtitle("Building 3 Consumption Forecasts")
  
```


```{r}
Oct_fit_building4 <- data_Building4_random %>%
  model(STl = my_dcmp_spec)

Oct_fit_building4_fc <- Oct_fit_building4 %>%
  forecast(h = 2880)

p4 <- Oct_fit_building4_fc %>%
  autoplot(color = 'purple') + ylim(c(0,10)) + ggtitle("Building 4 Consumption Forecasts")
  
```

```{r}
Oct_fit_building5 <- data_Building5_random %>%
  model(STl = my_dcmp_spec)

Oct_fit_building5_fc <- Oct_fit_building5 %>%
  forecast(h = 2880)

p5 <- Oct_fit_building5_fc %>%
  autoplot(color = 'orange') + ylim(c(0,50)) + ggtitle("Building 5 Consumption Forecasts")
  
```

```{r}
Oct_fit_building6 <- data_Building6_condensed %>%
  model(STl = my_dcmp_spec)

Oct_fit_building6_fc <- Oct_fit_building6 %>%
  forecast(h = 2880)

p6 <- Oct_fit_building6_fc %>%
  autoplot(color = 'yellow') + ylim(c(0,45)) + ggtitle("Building 6 Consumption Forecasts")
  
```

```{r}
Oct_fit_Solar0 <- data_Solar0 %>%
  model(STl = my_dcmp_spec)

Oct_fit_Solar0_fc <- Oct_fit_Solar0 %>%
  forecast(h = 2880)

p7 <- Oct_fit_Solar0_fc %>%
  autoplot(color = 'red') + ylim(c(0,50)) + ggtitle("Solar Panel 0 Production Forecasts")
  
```

```{r}
Oct_fit_Solar1 <- data_Solar1 %>%
  model(STl = my_dcmp_spec)

Oct_fit_Solar1_fc <- Oct_fit_Solar1 %>%
  forecast(h = 2880)

p8 <- Oct_fit_Solar1_fc %>%
  autoplot() + ylim(c(0,30)) + ggtitle("Solar Panel 1 Production Forecasts")
  
```

```{r}
Oct_fit_Solar2 <- data_Solar2 %>%
  model(STl = my_dcmp_spec)

Oct_fit_Solar2_fc <- Oct_fit_Solar2 %>%
  forecast(h = 2880)

p9 <- Oct_fit_Solar2_fc %>%
  autoplot(color = 'green') + ylim(c(0,30)) + ggtitle("Solar Panel 2 Production Forecasts")
  
```

```{r}
Oct_fit_Solar3 <- data_Solar3 %>%
  model(STl = my_dcmp_spec)

Oct_fit_Solar3_fc <- Oct_fit_Solar3 %>%
  forecast(h = 2880)

p10 <- Oct_fit_Solar3_fc %>%
  autoplot(color ='purple') + ylim(c(0,50)) + ggtitle("Solar Panel 3 Production Forecasts")
  
```

```{r}
Oct_fit_Solar4 <- data_Solar4 %>%
  model(STl = my_dcmp_spec)

Oct_fit_Solar4_fc <- Oct_fit_Solar4 %>%
  forecast(h = 2880)

p11 <- Oct_fit_Solar4_fc %>%
  autoplot(color = 'orange') + ylim(c(0,30)) + ggtitle("Solar Panel 4 Production Forecasts")
  
```

```{r}
Oct_fit_Solar5 <- data_Solar5 %>%
  model(STl = my_dcmp_spec)

Oct_fit_Solar5_fc <- Oct_fit_Solar5 %>%
  forecast(h = 2880)

p12 <- Oct_fit_Solar5_fc %>%
  autoplot(color = 'yellow') + ylim(c(0,50)) + ggtitle("Solar Panel 5 Production Forecasts")
  
```

```{r}
grid.arrange(p2,p3,p4,p5,p6)
```

```{r}
grid.arrange(p7, p8, p9, p10, p11, p12)
```

